# -*- coding: utf-8 -*-
"""test_camera.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OO1B4eqG4akWMUXcWR0gGARguKdgKaYC
"""

import cv2

cap = cv2.VideoCapture(0)

if not cap.isOpened():
    raise RuntimeError("Could not open camera")

while True:
    ret, frame = cap.read()
    if not ret:
        break

    cv2.imshow("Camera Test", frame)

    if cv2.waitKey(1) & 0xFF == 27:  # ESC
        break

cap.release()
cv2.destroyAllWindows()